laravel/app/routes.php
<?php
Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::any('ajaxnewsletter', array('as' => 'cadastro.newsletter', 'uses' => 'HomeController@cadastroNewsletter'));
Route::get('quem', array('as' => 'empresa', 'uses' => 'EmpresaController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::any('ajaxcontato', array('as' => 'contato.envio', 'uses' => 'ContatoController@envio'));

//Route::get('videos', array('as' => 'videos.index', 'uses' => 'VideosController@index'));
Route::get('videos', array('as' => 'videos.index', 'uses' => 'VideosController@todos'));

Route::get('videos/{categoria_slug?}', array('as' => 'videos.categorias', 'uses' => 'VideosController@categoria'));
Route::get('videos/{categoria_slug?}/{video_slug?}', array('as' => 'videos.detalhes', 'uses' => 'VideosController@detalhes'));

Route::any('busca', array('as' => 'videos.busca', 'uses' => 'VideosController@busca'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

Route::post('ajax/AdsLogImpressao', function(){

	$dados = array(
        \Input::get('i'),
        'impressao',
        \Input::get('l'),
        \Tools::ip(),
        $_SERVER['HTTP_USER_AGENT'],
        date('Y-m-d')
	);
	\DB::insert('insert into anuncios_estatisticas (anuncios_id, acao, url, ip, user_agent, created_at) values (?, ?, ?, ?, ?, ?)', $dados);
});

Route::post('ajax/AdsLogClick', function(){

	$dados = array(
        \Input::get('i'),
        'click',
        \Input::get('l'),
        \Tools::ip(),
        $_SERVER['HTTP_USER_AGENT'],
        date('Y-m-d')
	);
	\DB::insert('insert into anuncios_estatisticas (anuncios_id, acao, url, ip, user_agent, created_at) values (?, ?, ?, ?, ?, ?)', $dados);
});

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{

	Route::get('downloadCadastros', array('as' => 'painel.downloadCadastros', function(){
    	$filename = 'cadastros_'.date('d-m-Y-H-i-s');
		\Excel::create($filename, function($excel) {
		    $excel->sheet('Usuários Cadastrados', function($sheet) {
		        $sheet->fromModel(\Newsletter::select('nome', 'email')->orderBy('nome')->get());
		    });
		})->download('csv');
    }));

    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('empresa', 'Painel\EmpresaController');
Route::resource('contato', 'Painel\ContatoController');
Route::resource('contatosrecebidos', 'Painel\ContatosRecebidosController');
Route::resource('categorias', 'Painel\CategoriasController');
Route::resource('videos', 'Painel\VideosController');
Route::resource('newsletter', 'Painel\NewsletterController');
Route::resource('anuncios', 'Painel\AnunciosController');
Route::resource('calhaus', 'Painel\CalhausController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/Anuncios.php
<?php

class Anuncios extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'anuncios';

	protected $softDelete = true;

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function scopeFiltro($query, $value)
    {
    	if($value == '') return $query;

    	return $query->where('tipo_anuncio', $value);
    }

    public function scopePublicos($query)
    {
    	return $query->where('publicar', 1);
    }

    public function scopeAtivos($query)
    {
    	return $query->where('data_entrada', '<=', date('Y-m-d'))
    				 ->where('data_saida', '>=', date('Y-m-d'));
    }

	public function scopeOrdenado($query)
    {
    	return $query->orderBy('publicar', 'desc')
    				 ->orderBy('data_entrada', 'desc');
    }

    public function impressoes(){
        return $this->hasMany('AnunciosEstatisticas', 'anuncios_id')->where('acao', 'impressao');
    }

    public function clicks(){
        return $this->hasMany('AnunciosEstatisticas', 'anuncios_id')->where('acao', 'click');
    }

    public function ctr(){
        return (sizeof($this->clicks) == 0 || sizeof($this->impressoes) == 0) ? '--' : round(sizeof($this->clicks) / sizeof($this->impressoes), 4) * 100 . "%";
    }
}

laravel/app/controllers/painel/AnunciosController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, Anuncios;

class AnunciosController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	public function __construct(){
		\Validator::extend('exact_image_size', function($attribute, $value, $parameters)
		{
			// $parameters[0] = largura maxima
			// $parameters[1] = altura maxima

			$getFile = getimagesize(Input::file('arquivo')->getRealPath());
			// $getFile[0] largura do arquivo
			// $getFile[1] altura do arquivo

			return ($getFile[0] == $parameters[0]) && ($getFile[1] == $parameters[1]);
		});

	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$filtroTipo = Input::get('filtroTipo');

		$registros = Anuncios::filtro($filtroTipo)->ordenado()->paginate(25);

		$this->layout->content = View::make('backend.anuncios.index')->with(compact('registros', 'filtroTipo'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.anuncios.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$tipo_anuncio = Input::get('tipo');
		$tipo_arquivo = Input::get('tipo_arquivo');

		switch ($tipo_anuncio) {
			case 'premium':
				$dim = '940,90';
				$dim_msg = "940px x 90px";
				break;
			case 'lateral_grande_home':
				$dim = '250,250';
				$dim_msg = "250px x 250px";
				break;
			case 'lateral_grande_internas':
				$dim = '250,250';
				$dim_msg = "250px x 250px";
				break;
			case 'lateral_medio_home':
				$dim = '250,200';
				$dim_msg = "250px x 200px";
				break;
			case 'lateral_medio_internas':
				$dim = '250,200';
				$dim_msg = "250px x 200px";
				break;
			default:
				$dim = '';
				$dim_msg = "";
				break;
		}

		switch ($tipo_arquivo) {
			case 'flash':
				$mimes_permitidos = 'swf';
				break;
			case 'gif':
				$mimes_permitidos = 'gif';
				break;
			case 'imagem':
				$mimes_permitidos = 'jpeg,png';
				break;
			default:
				$mimes_permitidos = '';
				break;
		}

		$validation = \Validator::make(
			Input::all(),
			array(
				'titulo'       => 'required',
				'tipo'         => 'required|in:premium,lateral_grande_home,lateral_grande_internas,lateral_medio_home,lateral_medio_internas',
				'tipo_arquivo' => 'required|in:flash,gif,imagem',
				'arquivo'      => "required|mimes:{$mimes_permitidos}|exact_image_size:{$dim}",
				'link'         => 'required_if:tipo_arquivo,gif,imagem',
				'destino_link' => 'required_if:tipo_arquivo,gif,imagem|in:_blank,_self',
				'data_entrada' => 'required|date_format:d/m/Y',
				'data_saida'   => 'required|date_format:d/m/Y'
			),
			array(
				'exact_image_size' => "O arquivo deve ter o tamanho exato de : {$dim_msg}"
			)
		);

		if ($validation->fails()){
			// Coloca os dados informados na sessão para redirecionar de volta
			Session::flash('formulario', Input::except('arquivo'));

			return Redirect::back()->withErrors($validation);
		}

		$object = new Anuncios;
		$object->titulo = Input::get('titulo');
		$object->tipo_anuncio = $tipo_anuncio;
		$object->tipo_arquivo = $tipo_arquivo;
		$object->link = ($tipo_arquivo == 'flash') ? '' : Input::get('link');
		$object->destino_link = ($tipo_arquivo == 'flash') ? '' : Input::get('destino_link');
		$object->data_entrada = Tools::converteData(Input::get('data_entrada'));
		$object->data_saida = Tools::converteData(Input::get('data_saida'));
		$object->publicar = Input::get('publicar');

		// if($object->publicar == 1){
		// 	\DB::update('update anuncios set publicar = 0 where tipo_anuncio = ?', array($tipo_anuncio));
		// }

		$arquivo = Input::file('arquivo');
		$filename = $arquivo->getClientOriginalName();
		$arquivo->move('assets/ads/', $filename);
		$object->arquivo = $filename;

		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Anúncio criado com sucesso.');
			return Redirect::route('painel.anuncios.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::except('arquivo'));
			return Redirect::back()->withErrors(array('Erro ao criar Anúncio! '.$e->getMessage()));

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.anuncios.edit')->with('registro', Anuncios::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Anuncios::find($id);

		$tipo_anuncio_antigo = $object->tipo_anuncio;
		$tipo_arquivo_antigo = $object->tipo_arquivo;

		$tipo_anuncio = Input::get('tipo');
		$tipo_arquivo = Input::get('tipo_arquivo');

		switch ($tipo_anuncio) {
			case 'premium':
				$dim = '940,90';
				$dim_msg = "940px x 90px";
				break;
			case 'lateral_grande_home':
				$dim = '250,250';
				$dim_msg = "250px x 250px";
				break;
			case 'lateral_grande_internas':
				$dim = '250,250';
				$dim_msg = "250px x 250px";
				break;
			case 'lateral_medio_home':
				$dim = '250,200';
				$dim_msg = "250px x 200px";
				break;
			case 'lateral_medio_internas':
				$dim = '250,200';
				$dim_msg = "250px x 200px";
				break;
			default:
				$dim = '';
				$dim_msg = "";
				break;
		}

		switch ($tipo_arquivo) {
			case 'flash':
				$mimes_permitidos = 'swf';
				break;
			case 'gif':
				$mimes_permitidos = 'gif';
				break;
			case 'imagem':
				$mimes_permitidos = 'jpg,jpeg,png';
				break;
			default:
				$mimes_permitidos = '';
				break;
		}

		if($tipo_anuncio_antigo != $tipo_anuncio || $tipo_arquivo_antigo != $tipo_arquivo){

			$validation = \Validator::make(
				Input::all(),
				array(
					'titulo'       => 'required',
					'tipo'         => 'required|in:premium,lateral_grande_home,lateral_grande_internas,lateral_medio_home,lateral_medio_internas',
					'tipo_arquivo' => 'required|in:flash,gif,imagem',
					'arquivo'      => "sometimes|mimes:{$mimes_permitidos}|exact_image_size:{$dim}",
					'link'         => 'required_if:tipo_arquivo,gif,imagem',
					'destino_link' => 'required_if:tipo_arquivo,gif,imagem|in:_blank,_self',
					'data_entrada' => 'required|date_format:d/m/Y',
					'data_saida'   => 'required|date_format:d/m/Y'
				),
				array(
					'exact_image_size' => "O arquivo deve ter o tamanho exato de : {$dim_msg}"
				)
			);

		}else{

			$validation = \Validator::make(
				Input::all(),
				array(
					'titulo'       => 'required',
					'tipo'         => 'required|in:premium,lateral_grande_home,lateral_grande_internas,lateral_medio_home,lateral_medio_internas',
					'tipo_arquivo' => 'required|in:flash,gif,imagem',
					'link'         => 'required_if:tipo_arquivo,gif,imagem',
					'destino_link' => 'required_if:tipo_arquivo,gif,imagem|in:_blank,_self',
					'data_entrada' => 'required|date_format:d/m/Y',
					'data_saida'   => 'required|date_format:d/m/Y'
				)
			);
		}

		if ($validation->fails()){
			// Coloca os dados informados na sessão para redirecionar de volta
			Session::flash('formulario', Input::except('arquivo'));

			return Redirect::back()->withErrors($validation);
		}

		$object->titulo = Input::get('titulo');
		$object->tipo_anuncio = $tipo_anuncio;
		$object->tipo_arquivo = $tipo_arquivo;
		$object->link = ($tipo_arquivo == 'flash') ? '' : Input::get('link');
		$object->destino_link = ($tipo_arquivo == 'flash') ? '' : Input::get('destino_link');
		$object->data_entrada = Tools::converteData(Input::get('data_entrada'));
		$object->data_saida = Tools::converteData(Input::get('data_saida'));
		$object->publicar = Input::get('publicar');

		// if($object->publicar == 1){
		// 	\DB::update('update anuncios set publicar = 0 where tipo_anuncio = ? AND id != ?', array($tipo_anuncio, $id));
		// }

		if(Input::file('arquivo')){
			$arquivo = Input::file('arquivo');
			$filename = $arquivo->getClientOriginalName();
			$arquivo->move('assets/ads/', $filename);
			$object->arquivo = $filename;
		}

		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Anúncio alterado com sucesso.');
			return Redirect::route('painel.anuncios.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Anúncio! '.$e->getMessage()));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Anuncios::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Anúncio removido com sucesso.');

		return Redirect::route('painel.anuncios.index');
	}

}

laravel/app/views/backend/anuncios/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Anúncio
        </h2>

		<form action="{{URL::route('painel.anuncios.store')}}" method="post" enctype="multipart/form-data" novalidate>
			<div class="pad">

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif

				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" @if(Session::has('formulario')) value="{{ Session::get('formulario.titulo') }}" @endif required>
				</div>

				<div class="form-group">
					<label for="inputTipo">Tipo</label>
					<select	name="tipo" class="form-control" id="inputTipo" required>
						<option value="">Selecione</option>
						<option value="premium" data-dimensions="940px x 90px" @if(Session::has('formulario') && Session::get('formulario.tipo') == 'premium') selected @endif >Anúncio Premium - 940px x 90px</option>
						<option value="lateral_grande_home" data-dimensions="250px x 250px" @if(Session::has('formulario') && Session::get('formulario.tipo') == 'lateral_grande_home') selected @endif >Anúncio Lateral para Home (grande) - 250px x 250px</option>
            <option value="lateral_medio_home" data-dimensions="250px x 200px" @if(Session::has('formulario') && Session::get('formulario.tipo') == 'lateral_medio_home') selected @endif >Anúncio Lateral para Home (médio) - 250px x 200px</option>
            <option value="lateral_grande_internas" data-dimensions="250px x 250px" @if(Session::has('formulario') && Session::get('formulario.tipo') == 'lateral_grande_internas') selected @endif >Anúncio Lateral para Internas(grande) - 250px x 250px</option>
              <option value="lateral_medio_internas" data-dimensions="250px x 200px" @if(Session::has('formulario') && Session::get('formulario.tipo') == 'lateral_medio_internas') selected @endif >Anúncio Lateral para Internas(médio) - 250px x 200px</option>
					</select>
				</div>

				<div class="form-group">
					<label for="inputTipoArquivo">Tipo de Arquivo</label>
					<select	name="tipo_arquivo" class="form-control" id="inputTipoArquivo" required>
						<option value="">Selecione</option>
						<option value="flash" @if(Session::has('formulario') && Session::get('formulario.tipo_arquivo') == 'flash') selected @endif >Flash (SWF)</option>
						<option value="gif" @if(Session::has('formulario') && Session::get('formulario.tipo_arquivo') == 'gif') selected @endif >GIF</option>
						<option value="imagem" @if(Session::has('formulario') && Session::get('formulario.tipo_arquivo') == 'imagem') selected @endif >Imagem (JPG ou PNG)</option>
					</select>
				</div>

				<div class="form-group" id="hasInputArquivo" style="display:none;">
					<label for="inputArquivo">Arquivo <span id="file_dimensions_tip"></span> </label>
					<input type="file" class="form-control" id="inputArquivo" name="arquivo" required>
				</div>

				<div id="hasInputLinks" style="display:none;">

					<div class="form-group">
						<label for="inputLink">Link</label>
						<input type="text" class="form-control" id="inputLink" name="link" @if(Session::has('formulario')) value="{{ Session::get('formulario.link') }}" @endif >
					</div>

					<div class="form-group">
						<label for="inputDestino do Link">Destino do Link</label>
						<select	name="destino_link" class="form-control" id="inputDestino do Link" >
							<option value="">Selecione</option>
							<option value="_blank" @if(Session::has('formulario') && Session::get('formulario.destino_link') == '_blank') selected @endif >Nova Aba</option>
							<option value="_self" @if(Session::has('formulario') && Session::get('formulario.destino_link') == '_self') selected @endif >Mesma Aba</option>
						</select>
					</div>
				</div>

				<hr>

				<div class="well">

					<label>Período de Exibição</label>

					<hr>

					<div class="form-group">
						<label for="inputData de Entrada">Data de Início</label>
						<input type="text" class="form-control datepicker" id="inputData de Entrada" name="data_entrada" @if(Session::has('formulario')) value="{{ Session::get('formulario.data_entrada') }}" @endif required>
					</div>

					<div class="form-group">
						<label for="inputData de Saída">Data de Saída</label>
						<input type="text" class="form-control datepicker" id="inputData de Saída" name="data_saida" @if(Session::has('formulario')) value="{{ Session::get('formulario.data_saida') }}" @endif required>
					</div>

				</div>

				<hr>

				<div class="well">
					<div class="form-group">
						<label><input type="checkbox" name="publicar" value="1"> O anúncio está pronto para ser Publicado</label>
					</div>
				</div>

				<hr>

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.anuncios.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>

@stop

laravel/app/views/backend/anuncios/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Anúncios <a href='{{ URL::route('painel.anuncios.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Anúncio</a>
    </h2>

    <hr>

    <div class="btn-group">
        <a href="{{ URL::route('painel.anuncios.index', array('filtroTipo' => 'premium')) }}" title="" class="btn btn-sm btn-info @if($filtroTipo == 'premium') btn-warning @endif ">Premium</a>
        <a href="{{ URL::route('painel.anuncios.index', array('filtroTipo' => 'lateral_grande_home')) }}" title="" class="btn btn-sm btn-info @if($filtroTipo == 'lateral_grande_home') btn-warning @endif ">Lateral para Home (grande)</a>
        <a href="{{ URL::route('painel.anuncios.index', array('filtroTipo' => 'lateral_medio_home')) }}" title="" class="btn btn-sm btn-info @if($filtroTipo == 'lateral_medio_home') btn-warning @endif ">Lateral para Home (médio)</a>
        <a href="{{ URL::route('painel.anuncios.index', array('filtroTipo' => 'lateral_grande_internas')) }}" title="" class="btn btn-sm btn-info @if($filtroTipo == 'lateral_grande_internas') btn-warning @endif ">Lateral para Internas (grande)</a>
        <a href="{{ URL::route('painel.anuncios.index', array('filtroTipo' => 'lateral_medio_internas')) }}" title="" class="btn btn-sm btn-info @if($filtroTipo == 'lateral_medio_internas') btn-warning @endif ">Lateral para Internas (médio)</a>
    </div>

    <table class='table table-striped table-bordered table-hover'>

        <thead>
            <tr>
				<th rowspan="2">Publicado</th>
                <th rowspan="2">Título</th>
                <th rowspan="2">Período de Exibição</th>
                <th colspan="3" style='text-align:center;'>Estatísticas</th>
                <th rowspan="2"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
            <tr>
                <th>Clicks</th>
                <th>Impressões</th>
                <th>CTR <span class="glyphicon glyphicon-question-sign" data-toggle="tooltip" data-placement="top" title="A CTR (click-through rate) ou Taxa de Cliques é o número de cliques recebidos pelo anúncio dividido pelo número de vezes que ele é exibido (impressões)"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
				<td>
                    @if($registro->publicar == 1)
                        <span class="glyphicon glyphicon-ok"></span>
                    @else
                        <span class="glyphicon glyphicon-remove"></span>
                    @endif
                </td>
                <td>{{ $registro->titulo }}</td>
                <td>
                    Início: {{ Tools::converteData($registro->data_entrada) }}
                    <br>
                    Término: {{ Tools::converteData($registro->data_saida) }}
                </td>
                <td>
                    {{ sizeof($registro->clicks) }}
                </td>
                <td>
                    {{ sizeof($registro->impressoes) }}
                </td>
                <td>
                    {{ $registro->ctr() }}
                </td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.anuncios.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
          					{{ Form::open(array('route' => array('painel.anuncios.destroy', $registro->id), 'method' => 'delete')) }}
          						<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
          					{{ Form::close() }}
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    {{ $registros->links() }}
</div>

@stop