laravel/app/routes.php
<?php
Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::any('ajaxnewsletter', array('as' => 'cadastro.newsletter', 'uses' => 'HomeController@cadastroNewsletter'));
Route::get('quem', array('as' => 'empresa', 'uses' => 'EmpresaController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::any('ajaxcontato', array('as' => 'contato.envio', 'uses' => 'ContatoController@envio'));

//Route::get('videos', array('as' => 'videos.index', 'uses' => 'VideosController@index'));
Route::get('videos', array('as' => 'videos.index', 'uses' => 'VideosController@todos'));

Route::get('videos/{categoria_slug?}', array('as' => 'videos.categorias', 'uses' => 'VideosController@categoria'));
Route::get('videos/{categoria_slug?}/{video_slug?}', array('as' => 'videos.detalhes', 'uses' => 'VideosController@detalhes'));

Route::any('busca', array('as' => 'videos.busca', 'uses' => 'VideosController@busca'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

Route::post('ajax/AdsLogImpressao', function(){

	$dados = array(
        \Input::get('i'),
        'impressao',
        \Input::get('l'),
        \Tools::ip(),
        $_SERVER['HTTP_USER_AGENT'],
        date('Y-m-d')
	);
	\DB::insert('insert into anuncios_estatisticas (anuncios_id, acao, url, ip, user_agent, created_at) values (?, ?, ?, ?, ?, ?)', $dados);
});

Route::post('ajax/AdsLogClick', function(){

	$dados = array(
        \Input::get('i'),
        'click',
        \Input::get('l'),
        \Tools::ip(),
        $_SERVER['HTTP_USER_AGENT'],
        date('Y-m-d')
	);
	\DB::insert('insert into anuncios_estatisticas (anuncios_id, acao, url, ip, user_agent, created_at) values (?, ?, ?, ?, ?, ?)', $dados);
});

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{

	Route::get('downloadCadastros', array('as' => 'painel.downloadCadastros', function(){
    	$filename = 'cadastros_'.date('d-m-Y-H-i-s');
		\Excel::create($filename, function($excel) {
		    $excel->sheet('Usuários Cadastrados', function($sheet) {
		        $sheet->fromModel(\Newsletter::select('nome', 'email')->orderBy('nome')->get());
		    });
		})->download('csv');
    }));

    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('empresa', 'Painel\EmpresaController');
Route::resource('contato', 'Painel\ContatoController');
Route::resource('contatosrecebidos', 'Painel\ContatosRecebidosController');
Route::resource('categorias', 'Painel\CategoriasController');
Route::resource('videos', 'Painel\VideosController');
Route::resource('newsletter', 'Painel\NewsletterController');
Route::resource('anuncios', 'Painel\AnunciosController');
Route::resource('calhaus', 'Painel\CalhausController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/Categorias.php
<?php

class Categorias extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'categorias';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function scopeOrdenado($query)
    {
    	return $query->orderBy('ordem', 'asc');
    }

    public function scopeSlug($query, $slug)
    {
    	return $query->where('slug', '=', $slug);
    }

    public function scopeNotThis($query, $id)
    {
    	return $query->where('id', '!=', $id);
    }

    public function videos()
    {
        return $this->hasMany('Videos', 'categoria_id');
    }
}

laravel/app/controllers/painel/CategoriasController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, \Categorias;

class CategoriasController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.categorias.index')->with('registros', Categorias::ordenado()->get());		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.categorias.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Categorias;

		$object->titulo = Input::get('titulo');
		$object->slug = Str::slug(Input::get('titulo'));

		if(sizeof(Categorias::slug($object->slug)->get()) > 0){
			Session::flash('formulario.titulo', Input::get('titulo'));
			return Redirect::back()->withErrors(array('Erro ao criar Categoria! Uma categoria com o nome <b>'.$object->titulo.'</b> já existe'));
		}
		
		$imagem = Thumb::make('imagem', 100, 100, 'categorias/');
		if($imagem) $object->imagem = $imagem;

		//$imagem_hover = Thumb::make('imagem_hover', 100, 100, 'categorias/');
		//if($imagem) $object->imagem_hover = $imagem_hover;

		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Categoria criada com sucesso.');
			return Redirect::route('painel.categorias.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Categoria!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.categorias.edit')->with('registro', Categorias::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Categorias::find($id);

		$object->titulo = Input::get('titulo');
		$object->slug = Str::slug(Input::get('titulo'));
		
		if(sizeof(Categorias::slug($object->slug)->notThis($object->id)->get()) > 0){
			Session::flash('formulario.titulo', Input::get('titulo'));
			return Redirect::back()->withErrors(array('Erro ao alterar Categoria! Uma categoria com o nome <b>'.$object->titulo.'</b> já existe'));
		}


		$imagem = Thumb::make('imagem', 100, 100, 'categorias/');
		if($imagem) $object->imagem = $imagem;

		//$imagem_hover = Thumb::make('imagem_hover', 100, 100, 'categorias/');
		//if($imagem) $object->imagem_hover = $imagem_hover;

		
		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Categoria alterada com sucesso.');
			return Redirect::route('painel.categorias.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Categoria!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Categorias::find($id);

		$videos = $object->videos()->get();
		foreach ($videos as $key => $value) {
			$value->categoria_id = 0;
			$value->save();
		}

		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Categoria removida com sucesso.');

		return Redirect::route('painel.categorias.index');
	}

}

laravel/app/views/backend/categorias/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Categoria de Vídeo
        </h2>  

		{{ Form::open( array('route' => array('painel.categorias.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	


				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" value="{{$registro->titulo}}" required>
				</div>
				
				<div class="form-group">
					@if($registro->imagem)
						Imagem Atual<br>
						<img src="assets/img/categorias/{{$registro->imagem}}"><br>
					@endif
					<label for="inputImagem">Trocar Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem">
				</div>
				
				<!--
				<div class="form-group">
					@if($registro->imagem_hover)
						Imagem Atual<br>
						<img src="assets/images/categorias/{{$registro->imagem_hover}}"><br>
					@endif
					<label for="inputImagem">Trocar Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem_hover">
				</div>
				-->

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.categorias.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/categorias/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Categoria de Vídeo
        </h2>  

		<form action="{{URL::route('painel.categorias.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" @if(Session::has('formulario')) value="{{ Session::get('formulario.titulo') }}" @endif required>
				</div>
				
				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem" required>
				</div>
				<!--
				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem_hover" required>
				</div>
				-->
				

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.categorias.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/categorias/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Categorias de Vídeos <a href='{{ URL::route('painel.categorias.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Categoria</a>
    </h2>

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='categorias'>

        <thead>
            <tr>
                <th>Ordenar</th>
				<th>Título</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
				<td>{{ $registro->titulo }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.categorias.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
						{{ Form::open(array('route' => array('painel.categorias.destroy', $registro->id), 'method' => 'delete')) }}
							<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
						{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop